# Generated by Django 3.1.2 on 2020-11-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitgroup',
            name='cus',
            field=models.CharField(default='SDF', max_length=150),
            preserve_default=False,
        ),
    ]
