# Generated by Django 3.1.2 on 2020-10-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0002_customuser_google_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='google_uid',
            new_name='goo_uid',
        ),
    ]
