# Generated by Django 3.1.2 on 2020-10-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0003_auto_20201030_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharterdOfAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=10)),
                ('acc_status', models.IntegerField()),
                ('acc_type', models.IntegerField()),
            ],
        ),
    ]
