# Generated by Django 3.1.2 on 2020-10-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0004_charterdofaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterdofaccounts',
            name='acc_script',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
