# Generated by Django 3.1.2 on 2020-10-31 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0005_charterdofaccounts_acc_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('debit_amount', models.IntegerField()),
                ('credit_amount', models.IntegerField()),
                ('acc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incom.charterdofaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('to_acc', models.CharField(max_length=150)),
                ('acc_type', models.IntegerField()),
                ('acc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incom.charterdofaccounts')),
            ],
        ),
    ]
