# Generated by Django 3.1.2 on 2020-10-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0006_journalentry_tradedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterdofaccounts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incom.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incom.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incom.customuser'),
            preserve_default=False,
        ),
    ]
