# Generated by Django 3.1.2 on 2020-11-02 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0007_auto_20201031_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('acc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incom.charterdofaccounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
