# Generated by Django 3.1.2 on 2020-11-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0008_amountset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date_created',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='date_created',
            field=models.DateField(blank=True),
        ),
    ]
