# Generated by Django 3.1.2 on 2020-11-09 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0009_auto_20201109_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='desc',
            field=models.CharField(default='asd', max_length=150),
            preserve_default=False,
        ),
    ]
