# Generated by Django 3.1.2 on 2020-11-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0010_auto_20201109_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountset',
            name='set_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
