# Generated by Django 3.1.2 on 2020-11-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incom', '0011_amountset_set_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountset',
            name='tot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
